version: Build {build}
branches:
  only:
  - master
  - dev
skip_branch_with_pr: true
image: Visual Studio 2015
configuration: Release
platform:
- x86
- x64
- ARM
before_build:
- cmd: nuget restore
build:
  verbosity: minimal