version: Build {build}
branches:
  only:
  - master
  - dev
  - publish-test
skip_branch_with_pr: true
image: Visual Studio 2015
environment:
  clientSecret:
    secure: u2MqrnmS+4jSw1IQjBViTCmrVJ5OUo8bvswGz3HcF4L+qX2ZPYNrPRSKfOpWMUvr
build_script:
- ps: .\Build\Build.ps1
artifacts:
- path: '\Build\AppxPackages'
  name: AppxPackages
deploy_script:
- ps: >-
    if (($env:APPVEYOR_REPO_BRANCH -eq "publish-test") -and (-not [String]::IsNullOrEmpty($env:clientSecret)))
    {
        .\Publish\InstallStoreBroker.ps1
        .\Publish\AppVeyorInit.ps1
        .\Publish\PublishToStore.ps1
    }
